import type { Metadata } from "next";
import { Exo_2 } from "next/font/google";
import "./css/globals.css";

const inter = Exo_2({
  weight: ["300", "400", "500", "700"],
  subsets: ["cyrillic"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        {/* <Navbar /> */}
        {children}
      </body>
    </html>
  );
}
